from django.urls import path
from . import views

urlpatterns = [
    path('', views.board_list, name='board_list'),
    path('create/', views.board_create, name='board_create'),
    path('<int:pk>/', views.board_detail, name='board_detail'),
    path('<int:pk>/edit/', views.board_update, name='board_update'),
    path('<int:pk>/delete/', views.board_delete, name='board_delete'),
    path('<int:pk>/archivados/', views.board_archived, name='board_archived'),
    path('<int:pk>/members/', views.board_members, name='board_members'),
    path('<int:board_pk>/members/buscar/', views.board_member_search, name='board_member_search'),
    path('<int:board_pk>/members/<int:member_pk>/remove/', views.board_member_remove, name='board_member_remove'),
    path('<int:board_pk>/members/<int:member_pk>/set-role/', views.api_member_set_role, name='api_member_set_role'),
    path('<int:board_pk>/lists/create/', views.list_create, name='list_create'),
    path('lists/<int:pk>/delete/', views.list_delete, name='list_delete'),
    path('lists/<int:pk>/restaurar/', views.list_unarchive, name='list_unarchive'),
    path('lists/<int:pk>/eliminar-definitivo/', views.list_delete_permanent, name='list_delete_permanent'),
    path('lists/<int:pk>/reorder/', views.list_reorder, name='list_reorder'),
    path('lists/<int:list_pk>/cards/create/', views.card_create, name='card_create'),
    path('cards/<int:pk>/', views.card_detail, name='card_detail'),
    path('cards/<int:pk>/mover/', views.card_move, name='card_move'),
    path('cards/<int:pk>/delete/', views.card_delete, name='card_delete'),
    path('cards/<int:pk>/restaurar/', views.card_unarchive, name='card_unarchive'),
    path('cards/<int:pk>/eliminar-definitivo/', views.card_delete_permanent, name='card_delete_permanent'),
    path('<int:pk>/chat/enviar/', views.board_message_send, name='board_message_send'),
    path('<int:pk>/chat/bloquear/', views.board_toggle_chat_lock, name='board_toggle_chat_lock'),
    path('<int:board_pk>/labels/crear/', views.label_create, name='label_create'),
    path('cards/<int:card_pk>/comentarios/agregar/', views.comment_add, name='comment_add'),
    path('cards/<int:card_pk>/labels/toggle/', views.label_toggle, name='label_toggle'),
    path('comentarios/<int:pk>/eliminar/', views.comment_delete, name='comment_delete'),
    path('cards/<int:card_pk>/checklist/agregar/', views.checklist_item_add, name='checklist_item_add'),
    path('checklist/<int:pk>/toggle/', views.checklist_item_toggle, name='checklist_item_toggle'),
    path('checklist/<int:pk>/eliminar/', views.checklist_item_delete, name='checklist_item_delete'),
    path('buscar/', views.search, name='search'),
]
