# Generated by Django 6.0.5 on 2026-06-17 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workgroup',
            name='is_chat_locked',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
