# Generated by Django 6.0.3 on 2026-06-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
    ]
