# Generated by Django 6.0.6 on 2026-07-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_comment_label_card_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
